import '../RenderEngine/CoreEngine/collectElements.js'
import '../RenderEngine/CoreEngine/normalizeElements.js'
import '../RenderEngine/CoreEngine/computeScale.js'
import '../RenderEngine/CoreEngine/applyTransforms.js'
import '../RenderEngine/CoreEngine/exportCanvas.js'

import '../RenderEngine/FinalRender/setupRenderSurface.js'
import '../RenderEngine/FinalRender/elementCollector.js'
import '../RenderEngine/FinalRender/shapeRenderer.js'
import '../RenderEngine/FinalRender/textRenderer.js'
import '../RenderEngine/FinalRender/imageRenderer.js'
import '../RenderEngine/FinalRender/exporter.js'

import '../RenderEngine/Renderers/renderSquare.js'
import '../RenderEngine/Renderers/renderCircle.js'
import '../RenderEngine/Renderers/renderTriangle.js'
import '../RenderEngine/Renderers/renderText.js'
import '../RenderEngine/Renderers/renderImage.js'

import '../RenderEngine/Utilities/colorUtilities.js'
import '../RenderEngine/Utilities/contrastUtilities.js'
import '../RenderEngine/Utilities/textUtilities.js'

import '../RenderEngine/renderEngine.js'
import '../RenderEngine/renderCanvasButton.js'